name: cex
description: A new Flutter project

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.8.0
  http: ^1.1.0
  intl: ^0.18.1

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.1.5
  qr_flutter: ^4.1.0

  # State management & utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # GPS Dependencies
#  geolocator: ^11.0.0
#  permission_handler: ^11.4.3
#  permission_handler: ^12.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2

  google_maps_flutter: ^2.5.0

flutter:
  uses-material-design: true
